services:
  postgres-teatro:
    image: postgres:15-bookworm
    container_name: postgres-teatro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Utiliza variables de entorno para las configuraciones
# Se encuentran en el archivo .env

  app-teatro:
    build: .
    container_name: app-teatro
    depends_on:
      - postgres-teatro
    ports:
      - ${APP_PUERTO}:8080
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-teatro
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

volumes:
  postgres-data:
